version: '3'
services:
  app:
      build: .
      # image: fwyit/requetbin
      environment:
          REALM: prod
          REDIS_URL: "//redis:6379"
      links:
          - redis
      ports:
          - "8000:8000"

  redis:
      image: redis
